name: Salesforce Security RFI - Caller Workflow

on:
  issues:
    types: [opened]

jobs:
  label:
    uses: ./.github/workflows/workflow-A.yml
  project:
    needs: label
    uses: ./.github/workflows/workflow-B.yml
    secrets: inherit
