name: Identify and label RFI Issues

on:
  issues:
    types: [opened]

jobs:
  label:
    runs-on: ubuntu-latest
    name: ADD LABEL
    steps:
    - uses: actions/checkout@v2
    - uses: actions-ecosystem/action-add-labels@v1
      if: ${{ startsWith(github.event.issue.body, '# Security Request for Information (RFI)') }}
      with:
        labels: activity-security-questionnaire
  project:
    needs: label
    runs-on: ubuntu-latest
    name: ADD TO PROJECT
    steps:
    - uses: srggrs/assign-one-project-github-action@1.2.0
      if: |
        contains(github.event.issue.labels.*.name, 'activity-security-questionnaire')
      with:
        project: 'https://github.com/users/RaydioAM/projects/6'
        column_name: 'TestCol1'
